### ISSUE TITLE
[FR] CAN connectivity

### ISSUE THREAD

**Issue by Markus-1984** [beacon3d/beacon_klipper#1]
Hi friends,

I´ve just ordered beacon surface scanner a few days before. Is there a possiblity, maybe in the future, to connect beacon via CAN-Bus? It would be a great benefit on printers using a CAN toolhead board like the BTT EBB.

Kind regards
Markus

**Comment by dalegaard** [comment]
Hi @Markus-1984 

We don't have a CAN transceiver on the board and haven't been able to find one suitable for temperature, power budget, etc. CAN could be supported with a toolboard with USB host mode acting as a bridge, but it's not something Beacon itself will be supporting for the foreseeable future.

Best regards,
Lasse
