### ISSUE TITLE
Stuck when using beacon

### ISSUE THREAD

**Issue by oldChen3** [beacon3d/beacon_klipper#14]
question：During the process of using beacon to scan the heated bed, an error is reported:  Transition to shutdown state: MCU 'mcu' shutdown: Timer too close。
1. Is there any way to reduce beacon's requirements for CPU memory and CPU usage?
2. Are there any requirements for the tilt angle of beacon installation?

**Comment by Kirinkunhime** [comment]
Hi, please note that the Github issues are not intended to be used for general product support.

If you need further support, please join the Annex Discord server ( https://discord.gg/MzTR3zE ), and go to the #beacon_help_forum .

**Comment by oldChen3** [comment]
您的邮件已收到，谢谢。
