### ISSUE TITLE
G28 internal error when homing Z axis

### ISSUE THREAD

**Issue by Elevatormusic** [beacon3d/beacon_klipper#15]
After updating klipper attemps to home the Z axis result in a G28 internal error
beacon model revH

Some trouble shooting we ran through:
https://discord.com/channels/582187371529764864/1199533915912798268

![Screenshot_2024-01-24_121213](https://github.com/beacon3d/beacon_klipper/assets/22101396/55efea1e-3d15-4c93-877d-3c759f54225b)

**Comment by dalegaard** [comment]
Hi,

This was already fixed in afcd4e9.

Best regards,
Lasse
