### ISSUE TITLE
Updated klipper and Beacon causes Klipper start-up error : Unknown pin chip name 'probe'

### ISSUE THREAD

**Issue by betgear** [beacon3d/beacon_klipper#17]
Starting Klippy...
Args: ['/home/biqu/klipper/klippy/klippy.py', '/home/biqu/printer_data/config/printer.cfg', '-I', '/home/biqu/printer_data/comms/klippy.serial', '-l', '/home/biqu/printer_data/logs/klippy.log', '-a', '/home/biqu/printer_data/comms/klippy.sock']
Git version: 'v0.12.0-102-g9f41f53c'
Branch: master
Remote: origin
Tracked URL: https://github.com/Klipper3d/klipper
CPU: 4 core ?
Python: '3.9.2 (default, Feb 28 2021, 17:03:44) \n[GCC 10.2.1 20210110]'
Start printer at Tue Jan 30 14:38:07 2024 (1706625487.3 37.0)
===== Config file =====
[virtual_sdcard]
path = ~/printer_data/gcodes
on_error_gcode = CANCEL_PRINT

[pause_resume]

[display_status]

[respond]

[gcode_macro CANCEL_PRINT]
description = Cancel the actual running print
rename_existing = CANCEL_PRINT_BASE
gcode = 
	
	{% set client = printer['gcode_macro _CLIENT_VARIABLE']|default({}) %}
	{% set allow_park = client.park_at_cancel|default(false)|lower == 'true' %}
	{% set retract = client.cancel_retract|default(5.0)|abs %}
	
	{% set park_x = "" if (client.park_at_cancel_x|default(none) is none)
	else "X=" ~ client.park_at_cancel_x %}
	{% set park_y = "" if (client.park_at_cancel_y|default(none) is none)
	else "Y=" ~ client.park_at_cancel_y %}
	{% set custom_park = park_x|length > 0 or park_y|length > 0 %}
	
	
	{% if printer['gcode_macro RESUME'].restore_idle_timeout > 0 %}
	SET_IDLE_TIMEOUT TIMEOUT={printer['gcode_macro RESUME'].restore_idle_timeout}
	{% endif %}
	{% if (custom_park or not printer.pause_resume.is_paused) and allow_park %} _TOOLHEAD_PARK_PAUSE_CANCEL {park_x} {park_y} {% endif %}
	_CLIENT_RETRACT LENGTH={retract}
	TURN_OFF_HEATERS
	M106 S0
	{client.user_cancel_macro|default("")}
	SET_GCODE_VARIABLE MACRO=RESUME VARIABLE=idle_state VALUE=False
	
	SET_PAUSE_NEXT_LAYER ENABLE=0
	SET_PAUSE_AT_LAYER ENABLE=0 LAYER=0
	CANCEL_PRINT_BASE

[gcode_macro PAUSE]
description = Pause the actual running print
rename_existing = PAUSE_BASE
gcode = 
	
	{% set client = printer['gcode_macro _CLIENT_VARIABLE']|default({}) %}
	{% set idle_timeout = client.idle_timeout|default(0) %}
	{% set temp = printer[printer.toolhead.extruder].target if printer.toolhead.extruder != '' else 0 %}
	{% set restore = False if printer.toolhead.extruder == ''
	else True  if params.RESTORE|default(1)|int == 1 else False %}
	
	SET_GCODE_VARIABLE MACRO=RESUME VARIABLE=last_extruder_temp VALUE="{{'restore': restore, 'temp': temp}}"
	
	{% if idle_timeout > 0 %}
	SET_GCODE_VARIABLE MACRO=RESUME VARIABLE=restore_idle_timeout VALUE={printer.configfile.settings.idle_timeout.timeout}
	SET_IDLE_TIMEOUT TIMEOUT={idle_timeout}
	{% endif %}
	PAUSE_BASE
	{client.user_pause_macro|default("")}
	_TOOLHEAD_PARK_PAUSE_CANCEL {rawparams}

[gcode_macro RESUME]
description = Resume the actual running print
rename_existing = RESUME_BASE
variable_last_extruder_temp = {'restore': False, 'temp': 0}
variable_restore_idle_timeout = 0
variable_idle_state = False
gcode = 
	
	{% set client = printer['gcode_macro _CLIENT_VARIABLE']|default({}) %}
	{% set velocity = printer.configfile.settings.pause_resume.recover_velocity %}
	{% set sp_move = client.speed_move|default(velocity) %}
	{% set runout_resume = True if client.runout_sensor|default("") == ""
	else True if not printer[client.runout_sensor].enabled
	else printer[client.runout_sensor].filament_detected %}
	{% set can_extrude = True if printer.toolhead.extruder == ''
	else printer[printer.toolhead.extruder].can_extrude %}
	{% set do_resume = False %}
	{% set prompt_txt = [] %}
	
	
	{% if printer.idle_timeout.state|upper == "IDLE" or idle_state %}
	SET_GCODE_VARIABLE MACRO=RESUME VARIABLE=idle_state VALUE=False
	{% if last_extruder_temp.restore %}
	
	RESPOND TYPE=echo MSG='{"Restoring \"%s\" temperature to %3.1f\u00B0C, this may take some time" % (printer.toolhead.extruder, last_extruder_temp.temp) }'
	M109 S{last_extruder_temp.temp}
	{% set do_resume = True %}
	{% elif can_extrude %}
	{% set do_resume = True %}
	{% else %}
	RESPOND TYPE=error MSG='{"Resume aborted !!! \"%s\" not hot enough, please heat up again and press RESUME" % printer.toolhead.extruder}'
	{% set _d = prompt_txt.append("\"%s\" not hot enough, please heat up again and press RESUME" % printer.toolhead.extruder) %}
	{% endif %}
	
	{% elif can_extrude %}
	{% set do_resume = True %}
	{% else %}
	RESPOND TYPE=error MSG='{"Resume aborted !!! \"%s\" not hot enough, please heat up again and press RESUME" % printer.toolhead.extruder}'
	{% set _d = prompt_txt.append("\"%s\" not hot enough, please heat up again and press RESUME" % printer.toolhead.extruder) %}
	{% endif %}
	{% if runout_resume %}
	{% if do_resume %}
	{% if restore_idle_timeout > 0 %} SET_IDLE_TIMEOUT TIMEOUT={restore_idle_timeout} {% endif %}
	{client.user_resume_macro|default("")}
	_CLIENT_EXTRUDE
	RESUME_BASE VELOCITY={params.VELOCITY|default(sp_move)}
	{% endif %}
	{% else %}
	RESPOND TYPE=error MSG='{"Resume aborted !!! \"%s\" detects no filament, please load filament and press RESUME" % (client.runout_sensor.split(" "))[1]}'
	{% set _d = prompt_txt.append("\"%s\" detects no filament, please load filament and press RESUME" % (client.runout_sensor.split(" "))[1]) %}
	{% endif %}
	
	{% if not (runout_resume and do_resume) %}
	RESPOND TYPE=command MSG="action:prompt_begin RESUME aborted !!!"
	{% for element in prompt_txt %}
	RESPOND TYPE=command MSG='{"action:prompt_text %s" % element}'
	{% endfor %}
	RESPOND TYPE=command MSG="action:prompt_footer_button Ok|RESPOND TYPE=command MSG=action:prompt_end|info"
	RESPOND TYPE=command MSG="action:prompt_show"
	{% endif %}

[gcode_macro SET_PAUSE_NEXT_LAYER]
description = Enable a pause if the next layer is reached
gcode = 
	{% set pause_next_layer = printer['gcode_macro SET_PRINT_STATS_INFO'].pause_next_layer %}
	{% set ENABLE = params.ENABLE|default(1)|int != 0 %}
	{% set MACRO = params.MACRO|default(pause_next_layer.call, True) %}
	SET_GCODE_VARIABLE MACRO=SET_PRINT_STATS_INFO VARIABLE=pause_next_layer VALUE="{{ 'enable': ENABLE, 'call': MACRO }}"

[gcode_macro SET_PAUSE_AT_LAYER]
description = Enable/disable a pause if a given layer number is reached
gcode = 
	{% set pause_at_layer = printer['gcode_macro SET_PRINT_STATS_INFO'].pause_at_layer %}
	{% set ENABLE = params.ENABLE|int != 0 if params.ENABLE is defined
	else params.LAYER is defined %}
	{% set LAYER = params.LAYER|default(pause_at_layer.layer)|int %}
	{% set MACRO = params.MACRO|default(pause_at_layer.call, True) %}
	SET_GCODE_VARIABLE MACRO=SET_PRINT_STATS_INFO VARIABLE=pause_at_layer VALUE="{{ 'enable': ENABLE, 'layer': LAYER, 'call': MACRO }}"

[gcode_macro SET_PRINT_STATS_INFO]
rename_existing = SET_PRINT_STATS_INFO_BASE
description = Overwrite, to get pause_next_layer and pause_at_layer feature
variable_pause_next_layer = { 'enable': False, 'call': "PAUSE" }
variable_pause_at_layer = { 'enable': False, 'layer': 0, 'call': "PAUSE" }
gcode = 
	{% if pause_next_layer.enable %}
	RESPOND TYPE=echo MSG='{"%s, forced by pause_next_layer" % pause_next_layer.call}'
	{pause_next_layer.call}
	SET_PAUSE_NEXT_LAYER ENABLE=0
	{% elif pause_at_layer.enable and params.CURRENT_LAYER is defined and params.CURRENT_LAYER|int == pause_at_layer.layer %}
	RESPOND TYPE=echo MSG='{"%s, forced by pause_at_layer [%d]" % (pause_at_layer.call, pause_at_layer.layer)}'
	{pause_at_layer.call}
	SET_PAUSE_AT_LAYER ENABLE=0
	{% endif %}
	SET_PRINT_STATS_INFO_BASE {rawparams}

[gcode_macro _TOOLHEAD_PARK_PAUSE_CANCEL]
description = Helper: park toolhead used in PAUSE and CANCEL_PRINT
gcode = 
	
	{% set client = printer['gcode_macro _CLIENT_VARIABLE']|default({}) %}
	{% set velocity = printer.configfile.settings.pause_resume.recover_velocity %}
	{% set use_custom     = client.use_custom_pos|default(false)|lower == 'true' %}
	{% set custom_park_x  = client.custom_park_x|default(0.0) %}
	{% set custom_park_y  = client.custom_park_y|default(0.0) %}
	{% set park_dz        = client.custom_park_dz|default(2.0)|abs %}
	{% set sp_hop         = client.speed_hop|default(15) * 60 %}
	{% set sp_move        = client.speed_move|default(velocity) * 60 %}
	
	{% set origin    = printer.gcode_move.homing_origin %}
	{% set act       = printer.gcode_move.gcode_position %}
	{% set max       = printer.toolhead.axis_maximum %}
	{% set cone      = printer.toolhead.cone_start_z|default(max.z) %}
	{% set round_bed = True if printer.configfile.settings.printer.kinematics is in ['delta','polar','rotary_delta','winch']
	else False %}
	
	{% set z_min = params.Z_MIN|default(0)|float %}
	{% set z_park = [[(act.z + park_dz), z_min]|max, (max.z - origin.z)]|min %}
	{% set x_park = params.X       if params.X is defined
	else custom_park_x  if use_custom
	else 0.0            if round_bed
	else (max.x - 5.0) %}
	{% set y_park = params.Y       if params.Y is defined
	else custom_park_y  if use_custom
	else (max.y - 5.0)  if round_bed and z_park < cone
	else 0.0            if round_bed
	else (max.y - 5.0) %}
	
	_CLIENT_RETRACT
	{% if "xyz" in printer.toolhead.homed_axes %}
	G90
	G1 Z{z_park} F{sp_hop}
	G1 X{x_park} Y{y_park} F{sp_move}
	{% if not printer.gcode_move.absolute_coordinates %} G91 {% endif %}
	{% else %}
	RESPOND TYPE=echo MSG='Printer not homed'
	{% endif %}

[gcode_macro _CLIENT_EXTRUDE]
description = Extrudes, if the extruder is hot enough
gcode = 
	
	{% set client = printer['gcode_macro _CLIENT_VARIABLE']|default({}) %}
	{% set use_fw_retract = (client.use_fw_retract|default(false)|lower == 'true') and (printer.firmware_retraction is defined) %}
	{% set length = params.LENGTH|default(client.unretract)|default(1.0)|float %}
	{% set speed = params.SPEED|default(client.speed_unretract)|default(35) %}
	{% set absolute_extrude = printer.gcode_move.absolute_extrude %}
	
	{% if printer.toolhead.extruder != '' %}
	{% if printer[printer.toolhead.extruder].can_extrude %}
	{% if use_fw_retract %}
	{% if length < 0 %}
	G10
	{% else %}
	G11
	{% endif %}
	{% else %}
	M83
	G1 E{length} F{(speed|float|abs) * 60}
	{% if absolute_extrude %}
	M82
	{% endif %}
	{% endif %}
	{% else %}
	RESPOND TYPE=echo MSG='{"\"%s\" not hot enough" % printer.toolhead.extruder}'
	{% endif %}
	{% endif %}

[gcode_macro _CLIENT_RETRACT]
description = Retracts, if the extruder is hot enough
gcode = 
	{% set client = printer['gcode_macro _CLIENT_VARIABLE']|default({}) %}
	{% set length = params.LENGTH|default(client.retract)|default(1.0)|float %}
	{% set speed = params.SPEED|default(client.speed_retract)|default(35) %}
	
	_CLIENT_EXTRUDE LENGTH=-{length|float|abs} SPEED={speed|float|abs}

[board_pins EBB36_G0B1_v1.1]
mcu = can0
aliases = 
aliases_step = 
	EXT_EN=PD2,EXT_STEP=PD0,EXT_DIR=PD1,EXT_UART=PA15
aliases_limitsw = 
	LIMIT_1=PB6,LIMIT_2=PB5,LIMIT_3=PB7
aliases_fans = 
	FAN0=PA1,FAN1=PA0
aliases_thermistors = 
	TH0=PA3,PT100_CS=PA4,PT100_SCLK=PA5,PT100_MISO=PA6,PT100_MOSI=PA7
aliases_heaters = 
	HE0=PA2
aliases_rgb = 
	RGBLED=PD3
aliases_adxl = 
	ADXL_CS=PB12,ADXL_SCLK=PB10,ADXL_MISO=PB2,ADXL_MOSI=PB11
aliases_i2c = 
	AUX0=PB3,AUX1=PB4

[mcu can0]
canbus_uuid = 56240122e323
canbus_interface = can0

[temperature_sensor CANBOARD]
sensor_type = temperature_mcu
sensor_mcu = can0

[extruder]
step_pin = can0:PD0
dir_pin = can0:PD1
enable_pin = !can0:PD2
microsteps = 16
full_steps_per_rotation = 200
rotation_distance = 4.637
nozzle_diameter = 0.400
filament_diameter = 1.750
max_extrude_only_distance = 500.0
max_extrude_only_velocity = 120.0
heater_pin = can0:PB13
sensor_pin = can0:PA3
sensor_type = ATC Semitec 104NT-4-R025H42G
control = pid
pid_kp = 38.187
pid_ki = 5.092
pid_kd = 71.601
min_temp = -50
max_temp = 400

[tmc2209 extruder]
uart_pin = can0:PA15
stealthchop_threshold = 0
run_current = 0.85
hold_current = 0.100
sense_resistor = 0.110

[adxl345]
cs_pin = can0:ADXL_CS
spi_software_sclk_pin = can0:ADXL_SCLK
spi_software_mosi_pin = can0:ADXL_MOSI
spi_software_miso_pin = can0:ADXL_MISO
axes_map = x,y,z

[resonance_tester]
accel_chip = adxl345
probe_points = 175,175,20

[heater_fan heatbreak_cooling_fan]
pin = can0:PA0
heater = extruder
heater_temp = 50.0
fan_speed = 1.0

[stepper_x]
step_pin = PE6
dir_pin = !PE5
enable_pin = !PC14
microsteps = 16
rotation_distance = 40
endstop_pin = ^can0:PB7
position_endstop = 350
position_max = 350
homing_speed = 100

[tmc2209 stepper_x]
uart_pin = PC13
run_current = 0.851
hold_current = 0.500

[stepper_y]
step_pin = PE2
dir_pin = PE1
enable_pin = !PE4
microsteps = 16
rotation_distance = 40
endstop_pin = ^PF4
position_endstop = 350
position_max = 350
homing_speed = 100

[tmc2209 stepper_y]
uart_pin = PE3
run_current = 0.850
hold_current = 0.500

[stepper_z]
step_pin = PG9
dir_pin = PD7
enable_pin = !PG11
microsteps = 16
rotation_distance = 4
endstop_pin = probe:z_virtual_endstop
position_max = 400
position_min = -13.5
homing_speed = 10.0

[tmc2209 stepper_z]
uart_pin = PG10
run_current = 0.850
hold_current = 0.600

[stepper_z1]
step_pin = PD4
dir_pin = PD3
enable_pin = !PD6
microsteps = 16
rotation_distance = 4

[tmc2209 stepper_z1]
uart_pin = PD5
run_current = 0.850
hold_current = 0.600

[safe_z_home]
home_xy_position = 175,175
speed = 100
z_hop = 3
z_hop_speed = 5

[bed_mesh]
speed = 1000
algorithm = bicubic
horizontal_move_z = 8
mesh_min = 50, 50
mesh_max = 350, 350
probe_count = 100, 100

[heater_bed]
heater_pin = PF5
sensor_type = EPCOS 100K B57560G104F
sensor_pin = PB1
control = pid
pid_kp = 690.34
pid_ki = 111.47
pid_kd = 1068.83
min_temp = 0
max_temp = 130

[beacon]
serial = /dev/serial/by-id/usb-Beacon_Beacon_RevD_B1141B854E5737374D202020FF0A2427-if00
x_offset = 0
y_offset = -38
mesh_main_direction = x
mesh_runs = 2

[mcu]
canbus_uuid = 6978cdde9150
canbus_interface = can0

[filament_switch_sensor filament_sensor]
switch_pin = ^can0:LIMIT_2

[printer]
kinematics = corexy
max_velocity = 300
max_accel = 2500
max_z_velocity = 5
max_z_accel = 100
=======================
Config error
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/biqu/klipper/klippy/klippy.py", line 143, in _read_config
    m.add_printer_objects(config)
  File "/home/biqu/klipper/klippy/toolhead.py", line 658, in add_printer_objects
    config.get_printer().add_object('toolhead', ToolHead(config))
  File "/home/biqu/klipper/klippy/toolhead.py", line 261, in __init__
    self.kin = mod.load_kinematics(self, config)
  File "/home/biqu/klipper/klippy/kinematics/corexy.py", line 99, in load_kinematics
    return CoreXYKinematics(toolhead, config)
  File "/home/biqu/klipper/klippy/kinematics/corexy.py", line 12, in __init__
    self.rails = [stepper.LookupMultiRail(config.getsection('stepper_' + n))
  File "/home/biqu/klipper/klippy/kinematics/corexy.py", line 12, in <listcomp>
    self.rails = [stepper.LookupMultiRail(config.getsection('stepper_' + n))
  File "/home/biqu/klipper/klippy/stepper.py", line 423, in LookupMultiRail
    rail = PrinterRail(config, need_position_minmax,
  File "/home/biqu/klipper/klippy/stepper.py", line 304, in __init__
    self.add_extra_stepper(config)
  File "/home/biqu/klipper/klippy/stepper.py", line 383, in add_extra_stepper
    pin_params = ppins.parse_pin(endstop_pin, True, True)
  File "/home/biqu/klipper/klippy/pins.py", line 83, in parse_pin
    raise error("Unknown pin chip name '%s'" % (chip_name,))
pins.error: Unknown pin chip name 'probe'
webhooks client 281473738555200: New connection
webhooks client 281473738555200: Client info {'program': 'Moonraker', 'version': 'v0.8.0-294-g61ea860'}

**Comment by dalegaard** [comment]
Hi @betgear 

We don't provide support through Github, please visit us on Discord and we'll have someone help you out!

The most likely reason for your issue is the updater removing the `beacon.py` file. You can try running the `install.sh` script again in the Beacon directory.

Best regards,
Lasse
