### ISSUE TITLE
Implement mesh_min, mesh_max and probe_count like Klipper BED_MESH_CALIBRATE command

### ISSUE THREAD

**Issue by e76nystrom** [beacon3d/beacon_klipper#2]
Any possibility of doing this?

**Comment by dalegaard** [comment]
Hi @e76nystrom 

Yes this is on the roadmap, should land in a few days.

Best regards,
Lasse

**Comment by e76nystrom** [comment]
Sounds good.

Thank you

**Comment by dalegaard** [comment]
Hi @e76nystrom 

Can you test if the branch in #3 works for you? It should be ready to go, but I'd like to get it tested by someone other than just me before I hit the merge :-)

Best regards
Lasse

**Comment by dalegaard** [comment]
Hi @e76nystrom 

Thanks for testing it out! I'll merge :-)

Best regards,
Lasse
