### ISSUE TITLE
Can Beacon Contact be used to enhance normal Beacon mesh?

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [beacon3d/beacon_klipper#22]
Hello,

I have a Beacon H installed but due to the mount location I can't get it as close to the front of the bed as the rear. My question is can the upcoming Beacon Contact feature be used to probe this front section of the bed with the nozzle and add that in to the normal mesh the Beacon generates?

Thanks!

**Comment by dalegaard** [comment]
In theory this could be done but would introduce some risks in regards to probe offsets. It's not something we are planning for now.

Best regards,
Lasse
