### ISSUE TITLE
Z offset applied to probe last z result

### ISSUE THREAD

**Issue by trxgt05** [beacon3d/beacon_klipper#24]
While working on using contact to automatically set z offsets for a tool changing printer, I've noticed the last z result for thr probe has been changed to remove the z offset. This makes it confusing because the value in the console does not match the last z result. Is there a reason for this?

Klipper probe
![SmartSelect_20240602_150134_Chrome](https://github.com/beacon3d/beacon_klipper/assets/160454943/4bdb0bdf-2bce-46e8-9296-cdee43a3f4f8)

Beacon probe
![SmartSelect_20240602_150039_Chrome](https://github.com/beacon3d/beacon_klipper/assets/160454943/b253583a-e3ab-42f8-8e7b-45fee212e491)

**Comment by dalegaard** [comment]
This is to get a consistent result between proximity and contact probing. Both will return the same Z result for a given point.
