### ISSUE TITLE
FR: Print new z-offset when calling Z_OFFSET_APPLY_PROBE

### ISSUE THREAD

**Issue by jmwhelan** [beacon3d/beacon_klipper#7]
When adjusting z-offset during a print, and then issuing a Z_OFFSET_APPLY_PROBE command, it would be good to print out the new z-offset which is how it works with a BLTouch.

This would be good, because I can enter it manually in the printer.cfg instead of waiting for the print to end and call SAVE_CONFIG.

![image](https://user-images.githubusercontent.com/1584562/234730374-364e302b-d6c6-43dd-83c5-5ed6a0f9a9a4.png)

**Comment by sboschert** [comment]
I'd like to have this functionality, too. So I went ahead and created a PR: https://github.com/beacon3d/beacon_klipper/pull/13

**Comment by dalegaard** [comment]
Hi,

This was added today in 0a12243.

Best regards,
Lasse
