### ISSUE TITLE
Add support for zero_reference_position Klipper configuration parameter for bed_mesh

### ISSUE THREAD

**Issue by YanceyA** [beacon3d/beacon_klipper#9]
The Klipper bed_mesh configuration parameter zero_reference_position is now depreciated. The Klipper formal documentation now suggests the following: "Existing configurations using the relative_reference_index option must be updated to use the zero_reference_position."

However, zero_reference_position is not supported as a parameter in the Beacon code as confirmed by a Beacon developer via Discord. Can the beacon module be updated to use the zero_reference_position parameter currently recommended by Klipper? This parameter is more straight forward to use and easier to align this reference position to the Z home position.

Klipper documentation for these two parameters:
https://www.klipper3d.org/Bed_Mesh.html

**Comment by sdooweloc** [comment]
having this updated would be great please. Then we can all remove deprecated code from our configs and make sure we are at parity with Klipper's main branch.

**Comment by dalegaard** [comment]
This is supported now! Enjoy!

Best regards,
Lasse
